Guard against the adapter `close` function being undefined
If an adapter does not define a `close` function, a 'TypeError:
undefined is not a function' is thrown, causing the promise to enter a
rejected state. This PR guards against this.